# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58dee002ed43bee99330534b13e7b1bceb4e208613cd7bbbf00290643b48a6000b67b507e4e5190947d420b13167749944849df61ac633b1a9b089e67725d428

test:
  secret_key_base: 90b868a9bee42d29f23b7baa45fd3984e19026269e0b03102cc2fd086baf1571638dcdd6dd5143c46ba724cb1ac65f838576380d6be192abc86e43ab25bfc310

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
